CREATE TABLE cursos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL,
    categoria ENUM('FRONTEND', 'BACKEND', 'DEVOPS', 'ROBOTICS', 'IA') NOT NULL
);